export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_CUSTOMER = 'PENDING_CUSTOMER',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum TicketPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum TicketCategory {
  ACCOUNT_ISSUE = 'ACCOUNT_ISSUE',
  QUEST_BUG = 'QUEST_BUG',
  PAYOUT_DISPUTE = 'PAYOUT_DISPUTE',
  TECHNICAL_ERROR = 'TECHNICAL_ERROR',
}