export enum PuzzleSessionEventType {
  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_STARTED = 'SESSION_STARTED',
  PLAYER_JOINED = 'PLAYER_JOINED',
  PLAYER_LEFT = 'PLAYER_LEFT',
  PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED',
  PLAYER_RECONNECTED = 'PLAYER_RECONNECTED',
  SOLUTION_SUBMITTED = 'SOLUTION_SUBMITTED',
  PARTIAL_SOLUTION_UPDATED = 'PARTIAL_SOLUTION_UPDATED',
  HINT_DISCOVERED = 'HINT_DISCOVERED',
  PUZZLE_COMPLETED = 'PUZZLE_COMPLETED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
}
