/**
 * Standardized error codes for the Quest Service
 *
 * Naming convention: <DOMAIN>_<REASON>
 * These codes are stable, machine-readable identifiers that clients can branch on.
 */

export const ERROR_CODES = {
  // Base error codes
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  BAD_REQUEST: 'BAD_REQUEST',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Database errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',
  UNIQUE_CONSTRAINT_VIOLATION: 'UNIQUE_CONSTRAINT_VIOLATION',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  VALUE_TOO_LONG: 'VALUE_TOO_LONG',

  // Domain-specific errors
  INVALID_OPERATION: 'INVALID_OPERATION',
  DEPENDENCY_FAILURE: 'DEPENDENCY_FAILURE',
  TIMEOUT: 'TIMEOUT',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  INVALID_STATE: 'INVALID_STATE',

  // Quest-specific errors
  QUEST_NOT_FOUND: 'QUEST_NOT_FOUND',
  QUEST_ALREADY_COMPLETED: 'QUEST_ALREADY_COMPLETED',
  QUEST_EXPIRED: 'QUEST_EXPIRED',
  QUEST_UNAVAILABLE: 'QUEST_UNAVAILABLE',
  QUEST_PREREQUISITE_NOT_MET: 'QUEST_PREREQUISITE_NOT_MET',

  // Player/game errors
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  PLAYER_INSUFFICIENT_LEVEL: 'PLAYER_INSUFFICIENT_LEVEL',
  PLAYER_INSUFFICIENT_RESOURCES: 'PLAYER_INSUFFICIENT_RESOURCES',
  PLAYER_ALREADY_IN_QUEST: 'PLAYER_ALREADY_IN_QUEST',

  // Blockchain errors
  BLOCKCHAIN_NETWORK_UNREACHABLE: 'BLOCKCHAIN_NETWORK_UNREACHABLE',
  BLOCKCHAIN_TRANSACTION_FAILED: 'BLOCKCHAIN_TRANSACTION_FAILED',
  BLOCKCHAIN_CONTRACT_ERROR: 'BLOCKCHAIN_CONTRACT_ERROR',
  BLOCKCHAIN_INSUFFICIENT_FUNDS: 'BLOCKCHAIN_INSUFFICIENT_FUNDS',
  BLOCKCHAIN_TRANSACTION_TIMEOUT: 'BLOCKCHAIN_TRANSACTION_TIMEOUT',

  // External service errors
  EXTERNAL_SERVICE_UNAVAILABLE: 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_SERVICE_TIMEOUT: 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_INVALID_RESPONSE: 'EXTERNAL_SERVICE_INVALID_RESPONSE',
  EXTERNAL_SERVICE_QUOTA_EXCEEDED: 'EXTERNAL_SERVICE_QUOTA_EXCEEDED',

  // File/upload errors
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_INVALID_TYPE: 'FILE_INVALID_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_MISSING: 'FILE_MISSING',
  FILE_CORRUPT: 'FILE_CORRUPT',

  // Cache errors
  CACHE_UNAVAILABLE: 'CACHE_UNAVAILABLE',
  CACHE_KEY_NOT_FOUND: 'CACHE_KEY_NOT_FOUND',
  CACHE_WRITE_FAILED: 'CACHE_WRITE_FAILED',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

/**
 * Map HTTP status codes to error codes
 */
export function getErrorCodeFromStatus(status: number): ErrorCode {
  const statusMap: Record<number, ErrorCode> = {
    400: 'BAD_REQUEST',
    401: 'UNAUTHORIZED',
    403: 'FORBIDDEN',
    404: 'NOT_FOUND',
    409: 'CONFLICT',
    422: 'VALIDATION_ERROR',
    429: 'RATE_LIMIT_EXCEEDED',
    500: 'INTERNAL_SERVER_ERROR',
    503: 'SERVICE_UNAVAILABLE',
  };
  return statusMap[status] || 'INTERNAL_SERVER_ERROR';
}

/**
 * Error severity levels for logging and monitoring
 */
export enum ErrorSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

/**
 * Error categories for grouping and analysis
 */
export enum ErrorCategory {
  VALIDATION = 'VALIDATION',
  AUTHENTICATION = 'AUTHENTICATION',
  AUTHORIZATION = 'AUTHORIZATION',
  DATABASE = 'DATABASE',
  EXTERNAL_SERVICE = 'EXTERNAL_SERVICE',
  BUSINESS_LOGIC = 'BUSINESS_LOGIC',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  UNKNOWN = 'UNKNOWN',
}
