export enum ContentType {
  USER_PROFILE = 'USER_PROFILE',
  PUZZLE = 'PUZZLE',
  COMMENT = 'COMMENT',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  USERNAME = 'USERNAME',
  GUILD_NAME = 'GUILD_NAME',
  CUSTOM = 'CUSTOM',
}

export enum ModerationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED',
  AUTO_APPROVED = 'AUTO_APPROVED',
  AUTO_REJECTED = 'AUTO_REJECTED',
}

export enum ViolationCategory {
  PROFANITY = 'PROFANITY',
  SPAM = 'SPAM',
  HATE_SPEECH = 'HATE_SPEECH',
  HARASSMENT = 'HARASSMENT',
  INAPPROPRIATE = 'INAPPROPRIATE',
  MISINFORMATION = 'MISINFORMATION',
  SELF_HARM = 'SELF_HARM',
  VIOLENCE = 'VIOLENCE',
  NONE = 'NONE',
}

export enum Severity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ActionType {
  NONE = 'NONE',
  WARN = 'WARN',
  REMOVE_CONTENT = 'REMOVE_CONTENT',
  TEMPORARY_BAN = 'TEMPORARY_BAN',
  PERMANENT_BAN = 'PERMANENT_BAN',
  SHADOW_BAN = 'SHADOW_BAN',
  REQUIRE_REVIEW = 'REQUIRE_REVIEW',
}

export enum AppealStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum QueuePriority {
  LOW = 1,
  NORMAL = 2,
  HIGH = 3,
  URGENT = 4,
}

export enum AuditAction {
  FLAGGED = 'FLAGGED',
  REVIEWED = 'REVIEWED',
  APPEALED = 'APPEALED',
  APPEAL_RESOLVED = 'APPEAL_RESOLVED',
  ACTION_TAKEN = 'ACTION_TAKEN',
  ACTION_REVERTED = 'ACTION_REVERTED',
  AUTO_MODERATED = 'AUTO_MODERATED',
}
