version: '3.9'
services:
  integration-service:
    build: .
    ports:
      - "3009:3009"
    environment:
      - SERVICE_PORT=3009
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=integration_db
      - DB_SYNC=true
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: integration_db
    ports:
      - "5434:5432"
