export enum NotificationType {
  QUEST_ASSIGNED = 'QUEST_ASSIGNED',
  QUEST_COMPLETED = 'QUEST_COMPLETED',
  QUEST_APPROVED = 'QUEST_APPROVED',
  QUEST_REJECTED = 'QUEST_REJECTED',
  REWARD_RECEIVED = 'REWARD_RECEIVED',
  ACHIEVEMENT_UNLOCKED = 'ACHIEVEMENT_UNLOCKED',
  LEVEL_UP = 'LEVEL_UP',
  BADGE_EARNED = 'BADGE_EARNED',
  SYSTEM = 'SYSTEM',
}
