version: '3.9'
services:
  streaming-service:
    build: .
    ports:
      - "3011:3011"
    environment:
      - SERVICE_PORT=3011
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=streaming_db
      - DB_SYNC=true
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streaming_db
    ports:
      - "5436:5432"
