import {
    IsNotEmpty,
    IsString,
    IsUUID,
    IsISO8601,
    IsOptional,
    IsInt,
    Min,
    Max,
    IsObject,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/**
 * DTO for submitting a puzzle solution answer.
 * The `nonce` must be a UUID v4 generated by the client and used only once
 * (prevents replay attacks).
 */
export class SubmitSolutionDto {
    @ApiProperty({
        description:
            'The player\'s answer. Shape depends on puzzle content.type ' +
            '(e.g. index for multiple-choice, string for fill-blank, object for logic-grid).',
        example: 2,
    })
    @IsNotEmpty()
    answer: any;

    @ApiProperty({
        description:
            'Unique UUID v4 generated client-side for this submission. ' +
            'Re-using the same nonce will result in HTTP 409 (replay attack prevention).',
        example: '550e8400-e29b-41d4-a716-446655440000',
    })
    @IsUUID(4)
    nonce: string;

    @ApiProperty({
        description:
            'ISO-8601 timestamp of when the player started (received) this puzzle. ' +
            'Used server-side to compute elapsed time and enforce the time limit.',
        example: '2026-02-20T20:00:00.000Z',
    })
    @IsISO8601()
    sessionStartedAt: string;

    @ApiPropertyOptional({
        description: 'Number of hints the player used during this attempt.',
        example: 1,
        default: 0,
    })
    @IsOptional()
    @IsInt()
    @Min(0)
    @Max(10)
    hintsUsed?: number;

    @ApiPropertyOptional({
        description: 'Optional client-side metadata (user-agent, device info, etc.).',
        example: { platform: 'web', appVersion: '1.2.3' },
    })
    @IsOptional()
    @IsObject()
    clientMetadata?: Record<string, any>;
}
